DROP TABLE IF EXISTS book;

CREATE TABLE Book(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Name VARCHAR(250) NOT NULL,
  Description VARCHAR(250) DEFAULT NULL,
  Author VARCHAR(250) DEFAULT NULL,
  Classification VARCHAR(250) DEFAULT NULL,
  price float,
  ISBN VARCHAR(250) NOT NULL
);

DROP SEQUENCE IF EXISTS  BOOK_ID_SEQ;

CREATE SEQUENCE BOOK_ID_SEQ  MINVALUE 10  MAXVALUE 999  START WITH 10 INCREMENT BY 10 NOCACHE NOCYCLE;

INSERT INTO Book(Name , Description, Author,Classification,price , ISBN  ) VALUES
  ('Book1', 'Description1', 'Author1','COMIC',20.00,'ISBN1'),
  ('Book2', 'Description2', 'Author2','FICTION',10.25,'ISBN2');